version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: essential-framework
    container_name: essential_framework_php
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - minharede

networks:
  minharede:
    driver: bridge