version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: essential
    container_name: essential
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - minharede

networks:
  minharede:
    driver: bridge
